mybatis:
  mapper-locations: classpath:Mapper/*xml
  type-aliases-package: com.cduestc.dorm.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  port: 80
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cduestc_dorm?serverTimezone=GMT%2b8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
